### ISSUE TITLE
Infografia de librerias y componentes

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Ariadnamonserrat10#1]
[Infografia de librerias y componentes.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Ariadnamonserrat10/files/14565294/Infografia.de.librerias.y.componentes.pdf)

**Comment by josealfredo79** [comment]
@Ariadnamonserrat10 Falta la calificacion...

**Comment by Ariadnamonserrat10** [comment]
@josealfredo79 En la última clase comento que usted nos calificaría ya que ya no quedaba ningún grupo para que nos califique

**Comment by josealfredo79** [comment]
Bien hecho y revisado calificacion. 18
